//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdAndLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentUsageLog
    {
        public int Id { get; set; }
        public int StageId { get; set; }
        public int EquipmentId { get; set; }
        public decimal UsageHours { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ProductionStage ProductionStage { get; set; }
    }
}
