//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdAndLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionStage()
        {
            this.EquipmentUsageLogs = new HashSet<EquipmentUsageLog>();
            this.QualityDefects = new HashSet<QualityDefect>();
            this.WorkLogs = new HashSet<WorkLog>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int OperationId { get; set; }
        public Nullable<int> AssignedEmployeeId { get; set; }
        public Nullable<int> AssignedEquipmentId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int StatusId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Equipment Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentUsageLog> EquipmentUsageLogs { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
        public virtual TechOperation TechOperation { get; set; }
        public virtual ProductionStageStatu ProductionStageStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualityDefect> QualityDefects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkLog> WorkLogs { get; set; }
    }
}
