//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdAndLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReceipt
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int MaterialId { get; set; }
        public decimal ReceivedQuantity { get; set; }
        public Nullable<decimal> DefectQuantity { get; set; }
        public int WarehouseId { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
