//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdAndLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityDefect
    {
        public int Id { get; set; }
        public int StageId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DetectedAt { get; set; }
    
        public virtual ProductionStage ProductionStage { get; set; }
    }
}
