//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdAndLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechOperation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechOperation()
        {
            this.ProductionStages = new HashSet<ProductionStage>();
        }
    
        public int Id { get; set; }
        public int RouteId { get; set; }
        public string OperationName { get; set; }
        public int SequenceNumber { get; set; }
        public Nullable<decimal> DurationHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionStage> ProductionStages { get; set; }
        public virtual TechRoute TechRoute { get; set; }
    }
}
