//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdAndLog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkLog
    {
        public int Id { get; set; }
        public int StageId { get; set; }
        public int EmployeeId { get; set; }
        public decimal HoursWorked { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ProductionStage ProductionStage { get; set; }
    }
}
